# Generated by Django 4.2.24 on 2026-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hdmf_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='HDMF Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='philhealth_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PhilHealth Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sss_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SSS Number'),
        ),
    ]
