# Generated by Django 4.2.24 on 2026-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_hdmf_number_employee_philhealth_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tin_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TIN Number'),
        ),
    ]
