# Generated by Django 4.2.24 on 2026-04-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_department_code'),
        ('employee', '0003_employee_tin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='branch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='business_unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.businessunit', verbose_name='Business Unit'),
        ),
        migrations.AddField(
            model_name='employeeworkinformation',
            name='cost_center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.costcenter', verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='branch_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='business_unit_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.businessunit', verbose_name='Business Unit'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='cost_center_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.costcenter', verbose_name='Cost Center'),
        ),
    ]
