# Generated by Django 4.2.24 on 2026-04-21 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_add_branch_cost_center_business_unit_to_work_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetails',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Account'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_bank_details', to='employee.employee', verbose_name='Employee'),
        ),
    ]
