# Generated by Django 4.2.24 on 2026-04-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeeinsurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='any_other_code1',
        ),
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='any_other_code2',
        ),
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeebankdetails',
            name='state',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_extension',
            field=models.CharField(blank=True, help_text='e.g. Jr., Sr., III', max_length=20, null=True, verbose_name='Extension'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name'),
        ),
    ]
