# Generated by Django 4.2.24 on 2026-04-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employeebankdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('resigned', 'Resigned'), ('awol', 'AWOL'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=20, null=True, verbose_name='Employee Status'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('resigned', 'Resigned'), ('awol', 'AWOL'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=20, null=True, verbose_name='Employee Status'),
        ),
    ]
