# Generated by Django 4.2.24 on 2026-04-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_employeeworkinformation_employee_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegeneralsetting',
            name='badge_id_prefix',
            field=models.CharField(blank=True, default='PEP', max_length=5, null=True),
        ),
    ]
