# Generated by Django 4.2.24 on 2026-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employeegeneralsetting_badge_id_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinformation',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN'),
        ),
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN'),
        ),
    ]
