# Generated by Django 4.2.24 on 2026-04-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rename_badge_id_employee_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboardingPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0, help_text='0=set-password, 1=profile-photo, 2=personal-details, 3=bank-details, 4=done')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_portals', to='employee.employee', verbose_name='Employee')),
            ],
        ),
    ]
