# Generated by Django 4.2.24 on 2026-06-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinformation',
            name='employee_status',
            field=models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('awol', 'AWOL'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=20, verbose_name='Employee Status'),
        ),
        migrations.AlterField(
            model_name='historicalemployeeworkinformation',
            name='employee_status',
            field=models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('awol', 'AWOL'), ('terminated', 'Terminated'), ('retired', 'Retired')], default='active', max_length=20, verbose_name='Employee Status'),
        ),
    ]
