# Generated by Django 4.2.24 on 2026-06-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_payrollgroup_created_by_payrollgroup_modified_by_and_more'),
        ('employee', '0015_employeeworkinformation_payroll_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalemployeeworkinformation',
            name='payroll_group_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.payrollgroup', verbose_name='Payroll Group'),
        ),
    ]
