# Generated by Django 4.2.24 on 2026-07-06 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSSContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('range_from', models.FloatField(verbose_name='Range From')),
                ('range_to', models.FloatField(blank=True, null=True, verbose_name='Range To')),
                ('msc_regular_ss', models.FloatField(default=0.0, verbose_name='MSC Regular SS')),
                ('msc_mpf', models.FloatField(default=0.0, verbose_name='MSC MPF')),
                ('employer_regular_ss', models.FloatField(default=0.0, verbose_name='Employer Regular SS')),
                ('employer_mpf', models.FloatField(default=0.0, verbose_name='Employer MPF')),
                ('employer_ec', models.FloatField(default=0.0, verbose_name='Employer EC')),
                ('employee_regular_ss', models.FloatField(default=0.0, verbose_name='Employee Regular SS')),
                ('employee_mpf', models.FloatField(default=0.0, verbose_name='Employee MPF')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
