# Generated by Django 4.2.24 on 2026-07-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_seed_sss_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='is_sss',
            field=models.BooleanField(default=False, editable=False, help_text='Marks this deduction as the SSS contribution, whose amount is looked             up per employee from the SSS Contribution Table instead of a fixed             amount or rate.', verbose_name='SSS Contribution'),
        ),
    ]
