# Generated by Django 4.2.24 on 2026-07-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_add_tax_engine_to_payroll_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxbracket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taxbracket',
            name='filing_status_id',
        ),
        migrations.RemoveField(
            model_name='taxbracket',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='filing_status',
        ),
        migrations.RemoveField(
            model_name='historicalcontract',
            name='filing_status',
        ),
        migrations.RemoveField(
            model_name='payrollsettings',
            name='tax_engine',
        ),
        migrations.DeleteModel(
            name='FilingStatus',
        ),
        migrations.DeleteModel(
            name='TaxBracket',
        ),
    ]
