# Generated by Django 4.2.24 on 2026-07-08 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0024_seed_bir_withholding_tax_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='payslip_category',
            field=models.CharField(blank=True, choices=[('', 'None'), ('de_minimis', 'De Minimis'), ('wfh_utility_allowance', '(WFH) Utility Allowance'), ('non_taxable_allowance', 'Non Taxable Allowance'), ('adjustment_basic', 'Adjustment - Basic'), ('adjustment_nd_ot', 'Adjustment - ND & OT')], default='', help_text='Marks this allowance for a specific named row on the Philippine-style payslip layout (e.g. De Minimis, WFH Utility Allowance) instead of being grouped as a generic allowance.', max_length=30, null=True, verbose_name='Payslip Category'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='payslip_category',
            field=models.CharField(blank=True, choices=[('', 'None'), ('insurance', 'Insurance'), ('accountability', 'Accountability'), ('adjustment_basic', 'Adjustment - Basic'), ('adjustment_nd_ot', 'Adjustment - ND & OT')], default='', help_text='Marks this deduction for a specific named row on the Philippine-style payslip layout (e.g. Insurance, Accountability, Adjustment - Basic) instead of being grouped as a generic deduction.', max_length=30, null=True, verbose_name='Payslip Category'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='type',
            field=models.CharField(choices=[('loan', 'Loan'), ('advanced_salary', 'Advanced Salary'), ('fine', 'Penalty / Fine'), ('sss_loan', 'SSS Salary Loan'), ('pagibig_loan', 'HDMF (Pag-IBIG) Salary Loan')], default='loan', max_length=15),
        ),
        migrations.CreateModel(
            name='PerfectAttendanceBonusSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('bonus_amount', models.FloatField(default=0.0, help_text='Flat amount awarded when an employee has no late, undertime, or unpaid absence occurrences within the payroll period.', verbose_name='Bonus Amount')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable automatic Perfect Attendance Bonus eligibility checking during payslip generation.', verbose_name='Enabled')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
