# Generated by Django 4.2.24 on 2026-04-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_costcenter_businessunit_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code'),
        ),
    ]
