# Generated by Django 4.2.24 on 2026-07-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_employeeshiftschedule_is_rest_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotatingshift',
            name='rotation_type',
            field=models.CharField(choices=[('sequential', 'Sequential'), ('date_range', 'Date Range')], default='sequential', max_length=10, verbose_name='Rotation Type'),
        ),
        migrations.AlterField(
            model_name='historicalrotatingshiftassign',
            name='based_on',
            field=models.CharField(blank=True, choices=[('after', 'After'), ('weekly', 'Weekend'), ('monthly', 'Monthly')], max_length=10, null=True, verbose_name='Based On'),
        ),
        migrations.AlterField(
            model_name='rotatingshiftassign',
            name='based_on',
            field=models.CharField(blank=True, choices=[('after', 'After'), ('weekly', 'Weekend'), ('monthly', 'Monthly')], max_length=10, null=True, verbose_name='Based On'),
        ),
        migrations.CreateModel(
            name='RotatingShiftPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('last', 'Last Day')], max_length=10, verbose_name='Start Day')),
                ('end_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('last', 'Last Day')], max_length=10, verbose_name='End Day')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('rotating_shift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='base.rotatingshift', verbose_name='Rotating Shift')),
                ('shift_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.employeeshift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Rotating Shift Period',
                'verbose_name_plural': 'Rotating Shift Periods',
                'ordering': ['sequence'],
            },
        ),
    ]
