# Generated by Django 4.2.24 on 2026-05-15 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import horilla.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_dob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horilla_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('reject_reason', models.TextField(blank=True, max_length=255, null=True, verbose_name='Reject Reason')),
                ('fulfilled_document', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Fulfilled Document')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_document_requests', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Employee Document Request',
                'verbose_name_plural': 'Employee Document Requests',
            },
        ),
    ]
