# Generated by Django 4.2.24 on 2026-05-15 01:49

from django.db import migrations, models
import horilla.models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_documents', '0002_employeedocumentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocumentrequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Attachment'),
        ),
        migrations.AddField(
            model_name='employeedocumentrequest',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='employeedocumentrequest',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue Date'),
        ),
    ]
