# Generated by Django 4.2.24 on 2026-06-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_dob'),
        ('geofencing', '0002_branch_geofencing_exclusions'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofencing',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_geofences', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='geofencing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
