# Generated by Django 4.2.24 on 2026-04-07 07:38

from django.db import migrations, models
import horilla.models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Clock In Selfie'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='clock_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to=horilla.models.upload_path, verbose_name='Clock Out Selfie'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='location_verified',
            field=models.BooleanField(default=False, verbose_name='Location Verified'),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
