# Generated by Django 4.2.24 on 2026-04-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceactivity_selfie_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='gps_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='GPS Address'),
        ),
    ]
