# Generated by Codex on 2026-04-28

from django.db import migrations, models
from django.db.models import Q


def backfill_separate_clock_locations(apps, schema_editor):
    AttendanceActivity = apps.get_model("attendance", "AttendanceActivity")

    activities = AttendanceActivity.objects.filter(
        Q(latitude__isnull=False)
        | Q(longitude__isnull=False)
        | (Q(gps_address__isnull=False) & ~Q(gps_address=""))
    )

    for activity in activities.iterator():
        update_fields = []
        is_closed_activity = activity.clock_out is not None

        if is_closed_activity:
            if activity.clock_out_latitude is None and activity.latitude is not None:
                activity.clock_out_latitude = activity.latitude
                update_fields.append("clock_out_latitude")
            if activity.clock_out_longitude is None and activity.longitude is not None:
                activity.clock_out_longitude = activity.longitude
                update_fields.append("clock_out_longitude")
            if (
                not activity.clock_out_gps_address
                and activity.gps_address is not None
                and activity.gps_address != ""
            ):
                activity.clock_out_gps_address = activity.gps_address
                update_fields.append("clock_out_gps_address")
        else:
            if activity.clock_in_latitude is None and activity.latitude is not None:
                activity.clock_in_latitude = activity.latitude
                update_fields.append("clock_in_latitude")
            if activity.clock_in_longitude is None and activity.longitude is not None:
                activity.clock_in_longitude = activity.longitude
                update_fields.append("clock_in_longitude")
            if (
                not activity.clock_in_gps_address
                and activity.gps_address is not None
                and activity.gps_address != ""
            ):
                activity.clock_in_gps_address = activity.gps_address
                update_fields.append("clock_in_gps_address")

        if update_fields:
            activity.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_add_gps_address_to_attendanceactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceactivity",
            name="clock_in_gps_address",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Clock In GPS Address"
            ),
        ),
        migrations.AddField(
            model_name="attendanceactivity",
            name="clock_in_latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Clock In Latitude"),
        ),
        migrations.AddField(
            model_name="attendanceactivity",
            name="clock_in_longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Clock In Longitude"),
        ),
        migrations.AddField(
            model_name="attendanceactivity",
            name="clock_out_gps_address",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Clock Out GPS Address",
            ),
        ),
        migrations.AddField(
            model_name="attendanceactivity",
            name="clock_out_latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Clock Out Latitude"),
        ),
        migrations.AddField(
            model_name="attendanceactivity",
            name="clock_out_longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Clock Out Longitude"),
        ),
        migrations.RunPython(
            backfill_separate_clock_locations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
