# Generated by Django 4.2.24 on 2026-07-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendanceactivity_portal_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('import', 'Import')], default='website', max_length=10, verbose_name='Source'),
        ),
    ]
