# Generated by Django 4.2.24 on 2026-07-15 04:53

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendanceactivity_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceactivity',
            name='clock_in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to=attendance.models.attendance_selfie_upload_path, verbose_name='Clock In Selfie'),
        ),
        migrations.AlterField(
            model_name='attendanceactivity',
            name='clock_out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to=attendance.models.attendance_selfie_upload_path, verbose_name='Clock Out Selfie'),
        ),
    ]
