# Generated by Codex on 2026-09-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from attendance.methods.utils import validate_time_format


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_alter_attendanceactivity_source"),
        ("employee", "0020_alter_bank_modified_by"),
        ("base", "0013_remove_employeeshift_is_flexible"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePortalShiftOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        blank=True,
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "start_time",
                    models.TimeField(verbose_name="Start Time"),
                ),
                (
                    "end_time",
                    models.TimeField(verbose_name="End Time"),
                ),
                (
                    "minimum_working_hour",
                    models.CharField(
                        default="00:00",
                        max_length=10,
                        validators=[validate_time_format],
                        verbose_name="Minimum Working Hours",
                    ),
                ),
                (
                    "is_night_shift",
                    models.BooleanField(default=False, verbose_name="Night Shift"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portal_shift_overrides",
                        to="base.employeeshiftday",
                        verbose_name="Shift Day",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_shift_overrides",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Portal Shift Override",
                "verbose_name_plural": "Attendance Portal Shift Overrides",
            },
        ),
        migrations.CreateModel(
            name="AttendancePortalShiftContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        blank=True,
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
                (
                    "employee_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_shift_context",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "shift_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_shift_context",
                        to="base.employeeshift",
                        verbose_name="Portal Shift",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Portal Shift Context",
                "verbose_name_plural": "Attendance Portal Shift Contexts",
            },
        ),
        migrations.AddConstraint(
            model_name="attendanceportalshiftoverride",
            constraint=models.UniqueConstraint(
                fields=("employee_id", "day"),
                name="uniq_portal_shift_override_employee_day",
            ),
        ),
    ]
