# Generated by Codex on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0015_attendancescheduleoverride"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="notes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Notes",
            ),
        ),
        migrations.AddField(
            model_name="historicalattendance",
            name="notes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Notes",
            ),
        ),
    ]
